### PR TITLE
Update to Quarkus 1.6

### LINKED ISSUE #17: Update to Quarkus 1.6.0 to avoid errors with recent GraalVM versions
Server fails to build with recent GraalVM/Mandrel (e.g. 20.1.0):

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type jdk.internal.reflect.MethodAccessorGenerator is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
Call path from entry point to jdk.internal.reflect.ReflectionFactory.generateConstructor(Class, Constructor):
	at jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:513)
	at jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:506)
	at java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1531)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:509)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:83)
	at sun.security.pkcs11.SunPKCS11.initToken(SunPKCS11.java:1028)
	at sun.security.pkcs11.SunPKCS11$TokenPoller.run(SunPKCS11.java:852)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```

Quarkus 1.6 already deals with this (see [fix](https://github.com/quarkusio/quarkus/pull/9686)).

### PR DESCRIPTION
**Pull request by galderz**
Closes #17 

I couldn't get it to build (`mvn clean install -DskipTests`), but hopefully CI knows how to get it right:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy (copy-runner) on project infinispan-quarkus-integration-test-server: Unable to find/resolve artifact.: Could not find artifact org.infinispan:infinispan-quarkus-server-runner:bin:11.0.2-SNAPSHOT -> [Help 1]
```

### CODE REVIEW

**Comment by ryanemerson** [comment]
@galderz You need to execute `mvn clean install -Dnative`

**Comment by galderz** [comment]
@ryanemerson Ah yes, fixed that in my local builds.

**Comment by ryanemerson** [comment]
@galderz Sorry about the delay, we had to branch for the 12.x stream. Can you rebase on the latest master and repush. The CI should be able to run now

**Comment by ryanemerson** [comment]
Thanks for your commit @galderz, merged as part of https://github.com/infinispan/infinispan-quarkus/pull/21

**Pull request closed without merging**
