### PR TITLE
#110 Align command line to be the same as JVM mode

### PR DESCRIPTION
**Pull request by wburns**
https://github.com/infinispan/infinispan-quarkus/issues/110

### CODE REVIEW

**Comment by ryanemerson** [comment]
The `server-runner` module is failing, but AFAICT we don't need this module at all any more. We can remove this and just rely on the integration tests.

The `src/test/resources/opt/infinispan/bin/server.sh` path will need updating to be the same/similar to the one packaged with Infinispan.

**Comment by wburns** [comment]
Let me update those.

**Comment by wburns** [comment]
Updated tests which should pass now. Unfortunately, I can't seem to find any configuration of quarkus test annotations to run a custom command line that runs for the duration of the test. The QuarkusTest works for the duration but only for a quarkus app and QuarkusCommandTest requires the command app to complete and assert that. I tried to do something in between which uses a sleep and doesn't shut down, which is quite ugly.

I will try to ask the Quarkus guys later if there is a better alternative.

**Comment by ryanemerson** [comment]
IMO the tests in the `server-runner` don't really add any value as we already have coverage in `integration-tests/server`, so if there's no easy way to get them working I think we can remove them.

**Comment by wburns** [comment]
I ended up removing all the server-runner tests and it simplifies a lot of stuff.
I still think there is value in having the server-runner module to isolate the server extension. Extensions normally are not build in the final executable with Quarkus.

**Comment by ryanemerson** [comment]
I replayed the CI so that it would build with 14.0.0-SNAPSHOT and we're still getting failures. It seems the `server-runner` can't be built:

```java
Fatal error: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet6Address.
	at com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$9(ImageHeapScanner.java:611)
	at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of java.net.Inet6Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet6Address.
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:135)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:582)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
	at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:228)
	at com.oracle.svm.hosted.heap.SVMImageHeapScanner.transformFieldValue(SVMImageHeapScanner.java:126)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.onFieldValueReachable(ImageHeapScanner.java:331)
	at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$createImageHeapObject$3(ImageHeapScanner.java:272)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 10 more
```

**Comment by wburns** [comment]
Rebased on https://github.com/infinispan/infinispan-quarkus/pull/113 which has the fixes for the compilation error.

**Comment by ryanemerson** [comment]
Thanks @wburns

**Pull request merged**
