### PR TITLE
ISPN-11838 Native CLI

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.redhat.com/browse/ISPN-11838

Native counterpart to https://github.com/infinispan/infinispan/pull/8659

### CODE REVIEW

**Comment by ryanemerson** [comment]
Why do we need the maven wrapper? For Github actions?

**Comment by tristantarrant** [comment]
Yes, I want to get Linux, Windows and OSX native builds through GH Actions

**Comment by ryanemerson** [comment]
I'm getting some native errors with latest master:

```
Warning: class initialization of class io.netty.util.internal.logging.Log4JLogger failed with exception java.lang.NoClassDefFoundError: org/apache/log4j/Priority. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.netty.util.internal.logging.Log4JLogger to explicitly request delayed initialization of this class.
15:49:33,464 INFO  [org.inf.SECURITY] ISPN000947: Using Java SSL Provider
[infinispan-quarkus-cli-12.0.0-SNAPSHOT-runner:55403]     (clinit):     941.95 ms,  5.52 GB
[infinispan-quarkus-cli-12.0.0-SNAPSHOT-runner:55403]   (typeflow):  29,566.03 ms,  5.52 GB
[infinispan-quarkus-cli-12.0.0-SNAPSHOT-runner:55403]    (objects):  45,366.74 ms,  5.52 GB
[infinispan-quarkus-cli-12.0.0-SNAPSHOT-runner:55403]   (features):   7,055.34 ms,  5.52 GB
[infinispan-quarkus-cli-12.0.0-SNAPSHOT-runner:55403]     analysis:  87,217.99 ms,  5.52 GB
Error: Unsupported features in 2 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@42f0700d reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@7797e42c reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:248)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:372)
	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:313)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@469ec70b reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@7dab1355 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@5d95ae21 reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:119)
	at java.net.Socket.getInputStream(Socket.java:930)
	at org.openjdk.jmh.runner.link.BinaryLinkServer$Handler.<init>(BinaryLinkServer.java:272)
	at org.openjdk.jmh.runner.link.BinaryLinkServer$Acceptor.run(BinaryLinkServer.java:222)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@42f0700d reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@7797e42c reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:248)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:372)
	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:313)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@469ec70b reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@7dab1355 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@5d95ae21 reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:119)
	at java.net.Socket.getInputStream(Socket.java:930)
	at org.openjdk.jmh.runner.link.BinaryLinkServer$Handler.<init>(BinaryLinkServer.java:272)
	at org.openjdk.jmh.runner.link.BinaryLinkServer$Acceptor.run(BinaryLinkServer.java:222)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@42f0700d reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@7797e42c reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:248)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:372)
	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:313)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@469ec70b reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@7dab1355 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@5d95ae21 reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:119)
	at java.net.Socket.getInputStream(Socket.java:930)
	at org.openjdk.jmh.runner.link.BinaryLinkServer$Handler.<init>(BinaryLinkServer.java:272)
	at org.openjdk.jmh.runner.link.BinaryLinkServer$Acceptor.run(BinaryLinkServer.java:222)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)
	... 8 more
Error: Image build request failed with exit status 1

```

**Comment by ryanemerson** [comment]
Thanks @tristantarrant

**Pull request merged**
