### PR TITLE
Initialize DnsClient at runtime instead of reinitialize

### LINKED ISSUE #40: Error in native with Mandrel 20.3: Incompatible change of initialization policy for com.sun.jndi.dns.DnsClient
Error building native server with Mandrel 20.3. Binary does seem to get build though, see [here](https://gist.github.com/galderz/6d81577ccc0e1191e30de5ceeb85ac53).

```bash
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for com.sun.jndi.dns.DnsClient: trying to change RUN_TIME from feature com.oracle.svm.hosted.jdk.JDKInitializationFeature.afterRegistration to RERUN Quarkus
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:99)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insertRec(ClassInitializationConfiguration.java:113)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationConfiguration.insert(ClassInitializationConfiguration.java:64)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.rerunInitialization(ConfigurableClassInitialization.java:379)
	at io.quarkus.runner.AutoFeature.beforeAnalysis(AutoFeature.zig:1036)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:696)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:696)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
09:08:23,881 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
```

To reproduce, do the following:

1. Check out [qollider](https://github.com/galderz/qollider) repo and build it with maven and java 14, e.g. `mvn clean install`.

2. Install [JBang](https://github.com/jbangdev/jbang) and execute:

```bash
jbang -Dqollider.version=999-SNAPSHOT https://raw.githubusercontent.com/galderz/qollider/master/examples/infinispan_quarkus.java \
    --jdk https://github.com/openjdk/jdk11u-dev/commit/5ad383f7b802c9e8894e843a18acafd33569979f \
    --mandrel https://github.com/graalvm/mandrel/commit/2fc1ec0892574f14133c3796bf88448ccaaea28e \
    --infinispan https://github.com/wburns/infinispan/commit/8dce81940cfef3d18057158112610ddb9493172c \
    --quarkus https://github.com/galderz/quarkus/commit/c9741eafa7ee6b2f8b2919ba1869fcae2383a60c \
    --infinispan-quarkus https://github.com/galderz/infinispan-quarkus/commit/53ec46a4ed3ce4e9811296bde1fa28560114f7ce
```

This script will build JDK, Mandrel, Infinispan, Quarkus and Infinispan Quarkus projects, and then it produces 2 native servers: one with profiling and tracing and another a production one.

This issue should be assigned to @zakkak who's helping out with this.

### PR DESCRIPTION
**Pull request by zakkak**
Closes #40

### CODE REVIEW

**Review by galderz — APPROVED** [review]
Looks good, but I don't think there's a need to keep compatibility with Mandrel 20.2 since the native server AFAIK it's still experimental.

**Comment by zakkak** [comment]
In that case we can just remove the BuildStep.

**Comment by galderz** [comment]
Yeah I'd prefer that :)

**Comment by zakkak** [comment]
@galderz ready for review :)

**Review by galderz — APPROVED** [review]

**Comment by galderz** [comment]
@wburns @ryanemerson happy with this? can you integrate?

**Review by ryanemerson — APPROVED** [review]

**Comment by wburns** [comment]
Is fine with me, we should probably note that we require at least 20.3 somewhere too.

**Comment by zakkak** [comment]
> Is fine with me, we should probably note that we require at least 20.3 somewhere too.

Good point. Also https://github.com/infinispan/infinispan-quarkus/blob/0f446fcf310f8eb925fe36d1d154bf03cc350adc/.github/workflows/cli-release-linux.yml will need to be updated :)

**Comment by ryanemerson** [comment]
> Is fine with me, we should probably note that we require at least 20.3 somewhere too.

Hmm we probably need to update the CI as well. I'll check

**Comment by galderz** [comment]
Note that 20.3 is an LTS release, so it's suitable version to base things around.

**Comment by ryanemerson** [comment]
CI upgraded to have 20.3. Merged, thanks @zakkak

**Pull request merged**
