### PR TITLE
[11.x] Upgrade to Quarkus 1.7 (after 1.6 and 1.6.1) and fix the MBean server issues

### PR DESCRIPTION
**Pull request by galderz**
This is all to make Infinispan native server buildable with GraalVM 20.2. Let's see what CI says about that :)

### CODE REVIEW

**Comment by galderz** [comment]
Is CI set up correctly?

```
Error Failed to execute goal on project infinispan-quarkus-embedded: Could not resolve dependencies for project org.infinispan:infinispan-quarkus-embedded:jar:11.0.4-SNAPSHOT: The following artifacts could not be resolved: org.infinispan:infinispan-core:jar:11.0.4-SNAPSHOT, org.infinispan:infinispan-component-annotations:jar:11.0.4-SNAPSHOT: Could not find artifact org.infinispan:infinispan-core:jar:11.0.4-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public-jboss) -> [Help 1]
Indication 1
```

**Comment by ryanemerson** [comment]
> Is CI set up correctly?

The `Jenkinsfile` was created just to work with master originally. It  needs updating in order for it to work with Infinispan `11.0.x`. It's a case of adding `git checkout <target-branch>`  after the initial clone if not using master.

**Comment by ryanemerson** [comment]
@galderz Any reason you're issuing the upgrades against 11.0.x? 1.7.0.Final should only go in the next version.

**Comment by galderz** [comment]
Because 11.x is more stable than 12.x. Feel free to ignore the PR. It's just as guidance if/when you want those changes in master.

**Comment by galderz** [comment]
And hoped that the PR would trigger CI to verify it all worked fine :)

**Comment by ryanemerson** [comment]
I see. I actually already created https://github.com/infinispan/infinispan-quarkus/pull/24  to upgrade to 1.7, unfortunately there is an issue with logging that I haven't had a chance to properly look into

**Pull request closed without merging**
